"""Plain-language hyperparameter explanations."""

from __future__ import annotations


def _param(
    plain_language: str,
    algorithmic_role: str,
    typical_range: str,
    too_small: str,
    too_large: str,
    impact: str,
    tip: str,
) -> dict[str, str]:
    return {
        "plain_language": plain_language,
        "algorithmic_role": algorithmic_role,
        "typical_range": typical_range,
        "too_small": too_small,
        "too_large": too_large,
        "impact": impact,
        "tip": tip,
    }


HYPERPARAMETER_HELP = {
    "K-Nearest Neighbors": {
        "n_neighbors": _param(
            plain_language="How many nearby examples get to vote.",
            algorithmic_role="Sets the neighborhood size used to estimate the class.",
            typical_range="1 to 30 for small and medium teaching datasets.",
            too_small="The boundary becomes very flexible and noise-sensitive.",
            too_large="The model becomes too smooth and can miss local structure.",
            impact="Lower values reduce bias but raise variance.",
            tip="Start at 5, then sweep around it while watching the train-test gap.",
        ),
        "weights": _param(
            plain_language="How much influence close neighbors have compared with farther ones.",
            algorithmic_role="Changes the voting rule from equal votes to distance-weighted votes.",
            typical_range="uniform or distance.",
            too_small="Not applicable because this is a choice rather than a numeric scale.",
            too_large="Not applicable because this is a choice rather than a numeric scale.",
            impact="Distance weighting often reduces the effect of slightly farther noisy points.",
            tip="Try distance when borders are messy or classes overlap locally.",
        ),
        "metric": _param(
            plain_language="How distance is measured.",
            algorithmic_role="Defines what it means for two points to be similar.",
            typical_range="euclidean, manhattan, or minkowski.",
            too_small="Not applicable because this is a metric choice.",
            too_large="Not applicable because this is a metric choice.",
            impact="A different metric can rotate or stretch neighborhoods conceptually.",
            tip="Scale features first or the metric comparison will be misleading.",
        ),
    },
    "Decision Tree Classifier": {
        "max_depth": _param(
            plain_language="How many levels of questions the tree may ask.",
            algorithmic_role="Caps the recursive splitting depth.",
            typical_range="2 to 12 on many teaching datasets.",
            too_small="The tree may underfit because it cannot express enough rules.",
            too_large="The tree may memorize noise and create brittle leaves.",
            impact="Direct bias-variance control: shallow is biased, deep is high variance.",
            tip="Plot train and test score together rather than trusting depth alone.",
        ),
        "min_samples_split": _param(
            plain_language="How much evidence is needed before the tree can split a node.",
            algorithmic_role="Prevents very small internal nodes from being split further.",
            typical_range="2 to 20.",
            too_small="The tree can keep splitting tiny groups and overfit.",
            too_large="The tree may stop growing before learning useful structure.",
            impact="Higher values reduce flexibility and stabilize the tree.",
            tip="Increase it when training score is much higher than test score.",
        ),
        "min_samples_leaf": _param(
            plain_language="Minimum data points allowed in a final leaf.",
            algorithmic_role="Prevents leaves from becoming too tiny.",
            typical_range="1 to 20.",
            too_small="Leaves may become too specific to isolated cases.",
            too_large="Leaves may become too broad and blur class boundaries.",
            impact="Larger leaves smooth predictions and reduce variance.",
            tip="Useful when a dataset contains label noise.",
        ),
        "criterion": _param(
            plain_language="The score used to decide whether a split is good.",
            algorithmic_role="Measures impurity reduction.",
            typical_range="gini, entropy, or log_loss.",
            too_small="Not applicable because this is a criterion choice.",
            too_large="Not applicable because this is a criterion choice.",
            impact="The criterion changes the exact split preference, though behavior is often similar.",
            tip="Keep gini for baseline runs and compare entropy when teaching impurity ideas.",
        ),
    },
    "Random Forest Classifier": {
        "n_estimators": _param(
            plain_language="How many trees vote in the forest.",
            algorithmic_role="Controls ensemble size.",
            typical_range="100 to 300 for many demos.",
            too_small="Predictions can be noisy because the ensemble is not large enough.",
            too_large="Performance gains flatten while training time keeps growing.",
            impact="Mainly affects variance reduction and stability.",
            tip="Once the metric stabilizes, extra trees usually add little educational value.",
        ),
        "max_depth": _param(
            plain_language="How deep each tree can grow.",
            algorithmic_role="Controls complexity of the individual trees inside the forest.",
            typical_range="4 to 15.",
            too_small="Each tree may be too weak, so the forest underfits.",
            too_large="Trees become more variable and can overfit noisy details.",
            impact="Balances per-tree flexibility against ensemble stability.",
            tip="Depth and min_samples_leaf often tell a clearer story together than alone.",
        ),
        "max_features": _param(
            plain_language="How many features each split is allowed to inspect.",
            algorithmic_role="Introduces randomness so trees are less correlated.",
            typical_range="sqrt, log2, or all features.",
            too_small="Trees may miss useful splitting variables too often.",
            too_large="Trees become more similar, so averaging helps less.",
            impact="Controls diversity across trees, which is central to random forests.",
            tip="Use the Hyperparameter Lab to connect diversity with stability.",
        ),
        "min_samples_leaf": _param(
            plain_language="Minimum examples in each final leaf.",
            algorithmic_role="Smooths each individual tree.",
            typical_range="1 to 10.",
            too_small="Leaves can become noisy and highly specific.",
            too_large="Trees lose local detail and can underfit.",
            impact="Higher values reduce variance and often improve robustness.",
            tip="This is one of the cleanest overfitting controls for forests.",
        ),
    },
    "Support Vector Machine": {
        "C": _param(
            plain_language="How strongly the model tries to avoid training mistakes.",
            algorithmic_role="Sets the penalty for margin violations.",
            typical_range="0.01 to 100 on a log scale.",
            too_small="The separator is heavily regularized and may underfit.",
            too_large="The separator can become too sensitive to training points.",
            impact="Higher C lowers bias but raises variance.",
            tip="Always interpret C together with kernel and gamma.",
        ),
        "kernel": _param(
            plain_language="What shape of separator the SVM is allowed to build.",
            algorithmic_role="Defines the feature transformation used for similarity.",
            typical_range="linear, rbf, or poly.",
            too_small="Not applicable because kernel is categorical.",
            too_large="Not applicable because kernel is categorical.",
            impact="A linear kernel gives a simple boundary; RBF gives local flexibility.",
            tip="Compare linear and RBF on the same scaled dataset for a clean lesson.",
        ),
        "gamma": _param(
            plain_language="How local the influence of each point is for non-linear kernels.",
            algorithmic_role="Controls the width of the RBF or polynomial influence pattern.",
            typical_range="scale, auto, or small positive floats.",
            too_small="The boundary becomes very smooth and may underfit.",
            too_large="The boundary becomes very wiggly and may overfit.",
            impact="Higher gamma increases local flexibility.",
            tip="Gamma is easiest to understand with a decision-boundary plot.",
        ),
    },
    "Logistic Regression": {
        "C": _param(
            plain_language="Inverse strength of regularization.",
            algorithmic_role="Controls how much the coefficients are allowed to grow.",
            typical_range="0.01 to 100 on a log scale.",
            too_small="The decision boundary may become too simple.",
            too_large="The model may chase idiosyncrasies in the training data.",
            impact="Higher C lowers regularization and raises flexibility.",
            tip="If features are not scaled, C comparisons are harder to interpret.",
        ),
        "penalty": _param(
            plain_language="Type of coefficient shrinkage.",
            algorithmic_role="Changes how the optimization discourages complexity.",
            typical_range="l1 or l2.",
            too_small="Not applicable because penalty is categorical.",
            too_large="Not applicable because penalty is categorical.",
            impact="L1 can zero some coefficients; L2 shrinks them more smoothly.",
            tip="L1 is useful when you want to discuss sparse models.",
        ),
        "solver": _param(
            plain_language="Optimization method used to fit the coefficients.",
            algorithmic_role="Determines how the regularized objective is minimized.",
            typical_range="lbfgs, liblinear, or saga.",
            too_small="Not applicable because solver is categorical.",
            too_large="Not applicable because solver is categorical.",
            impact="Some solvers support more penalties or datasets than others.",
            tip="Solver changes optimization behavior, not the conceptual model family.",
        ),
    },
    "Gradient Boosting Classifier": {
        "n_estimators": _param(
            plain_language="Number of small trees added one after another.",
            algorithmic_role="Controls how many boosting steps the model takes.",
            typical_range="50 to 300.",
            too_small="The ensemble may stop before correcting enough errors.",
            too_large="The model can overfit if the learning rate is not small enough.",
            impact="More stages increase capacity.",
            tip="Interpret this together with learning_rate.",
        ),
        "learning_rate": _param(
            plain_language="How much each new tree changes the current ensemble.",
            algorithmic_role="Scales the contribution of every boosting stage.",
            typical_range="0.01 to 0.2 for many practical demos.",
            too_small="Learning may be too slow unless many estimators are added.",
            too_large="The model can overreact to each stage and overfit.",
            impact="Strong control over speed, flexibility, and stability.",
            tip="A smaller learning rate with more estimators often generalizes better.",
        ),
        "max_depth": _param(
            plain_language="Complexity of the individual weak learner trees.",
            algorithmic_role="Controls how much interaction each boosting stage can model.",
            typical_range="1 to 5.",
            too_small="Learners may be too weak to capture useful interactions.",
            too_large="Each stage becomes too expressive and can overfit quickly.",
            impact="Deeper learners increase flexibility and variance.",
            tip="Shallow learners make the additive boosting story easiest to see.",
        ),
    },
    "MLP Classifier": {
        "hidden_layer_sizes": _param(
            plain_language="The size of each hidden layer.",
            algorithmic_role="Sets network capacity and representation depth.",
            typical_range="One or two layers such as 50, 100, or 100,50.",
            too_small="The network may not have enough capacity to fit the structure.",
            too_large="The network may overfit or become harder to optimize.",
            impact="Directly changes flexibility, bias, and variance.",
            tip="Increase architecture size gradually instead of jumping to very deep networks.",
        ),
        "activation": _param(
            plain_language="The non-linear function used in hidden layers.",
            algorithmic_role="Creates non-linear transformations between layers.",
            typical_range="relu, tanh, or logistic.",
            too_small="Not applicable because activation is categorical.",
            too_large="Not applicable because activation is categorical.",
            impact="ReLU is often efficient; tanh can be smoother; logistic is more constrained.",
            tip="Use one activation at a time when teaching architecture effects.",
        ),
        "learning_rate_init": _param(
            plain_language="Initial step size for optimization.",
            algorithmic_role="Controls how quickly weights are updated during training.",
            typical_range="0.0001 to 0.01 for many demos.",
            too_small="Training may crawl and appear stuck.",
            too_large="Loss may oscillate or fail to converge.",
            impact="Affects stability and speed rather than raw capacity alone.",
            tip="If learning is unstable, lower this before changing the whole architecture.",
        ),
        "alpha": _param(
            plain_language="L2 regularization strength on network weights.",
            algorithmic_role="Discourages very large weights.",
            typical_range="0.00001 to 0.01.",
            too_small="The network can memorize noisy training examples.",
            too_large="The network may become too constrained and underfit.",
            impact="Higher alpha reduces variance but can increase bias.",
            tip="Useful when the training score keeps rising while test score stalls.",
        ),
        "batch_size": _param(
            plain_language="How many examples are processed per update.",
            algorithmic_role="Changes optimization noise and throughput.",
            typical_range="16 to 128.",
            too_small="Training becomes noisy and sometimes unstable.",
            too_large="Updates become smoother but may lose some regularizing noise.",
            impact="Affects stability and convergence behavior.",
            tip="Keep it moderate so the capacity lesson stays focused on other settings.",
        ),
        "max_iter": _param(
            plain_language="Maximum number of passes through the optimization routine.",
            algorithmic_role="Stops training after a fixed number of iterations.",
            typical_range="200 to 1000.",
            too_small="The network may stop before it has learned enough.",
            too_large="Training time grows, and overfitting can increase if other controls are weak.",
            impact="Changes convergence more than model family.",
            tip="If the solver has not converged, raising max_iter is often the first fix.",
        ),
    },
}


def get_hyperparameter_help(model_name: str) -> dict[str, dict[str, str]]:
    return HYPERPARAMETER_HELP.get(model_name, {})
