"""Plain-language model descriptions."""

from __future__ import annotations


def _entry(
    explanation: str,
    intuition: str,
    assumptions: list[str],
    strengths: list[str],
    weaknesses: list[str],
    use_cases: list[str],
    limitations: list[str],
    mistakes: list[str],
    visuals: list[str],
) -> dict[str, object]:
    return {
        "explanation": explanation,
        "intuition": intuition,
        "assumptions": assumptions,
        "strengths": strengths,
        "weaknesses": weaknesses,
        "use_cases": use_cases,
        "limitations": limitations,
        "beginner_mistakes": mistakes,
        "visuals": visuals,
    }


MODEL_HELP = {
    "Linear Regression": _entry(
        explanation="Predicts a number by combining features with learned weights.",
        intuition="Each feature pushes the prediction up or down by a fixed amount.",
        assumptions=["Relationship is roughly linear", "Errors are not dominated by strong outliers"],
        strengths=["Fast baseline", "Coefficients are easy to inspect"],
        weaknesses=["Misses strong non-linear structure", "Can struggle with correlated features"],
        use_cases=["Price prediction baseline", "Interpretable tabular problems"],
        limitations=["Needs feature engineering for curved patterns"],
        mistakes=["Using it on obviously non-linear data without checking residuals"],
        visuals=["Coefficient plot", "Prediction vs true", "Residual plot"],
    ),
    "Ridge Regression": _entry(
        explanation="Linear regression with a penalty that keeps weights from growing too large.",
        intuition="It prefers simpler weight patterns unless the data strongly supports larger coefficients.",
        assumptions=["Mostly linear signal", "Scaled features help interpretation"],
        strengths=["Stable with correlated features", "Good regularized baseline"],
        weaknesses=["Still linear", "Regularization can become too strong"],
        use_cases=["High-dimensional linear baselines", "When plain linear regression is unstable"],
        limitations=["Does not perform feature selection directly"],
        mistakes=["Forgetting that alpha changes the bias-variance balance"],
        visuals=["Coefficient plot", "Alpha sweep curve"],
    ),
    "Lasso Regression": _entry(
        explanation="Linear regression with a penalty that can force some coefficients to zero.",
        intuition="The penalty is strong enough that small feature effects may disappear completely.",
        assumptions=["Mostly linear signal", "Features should be scaled"],
        strengths=["Performs feature selection", "Produces sparse models"],
        weaknesses=["Can underfit if alpha is high", "May behave unstably with strongly correlated features"],
        use_cases=["Sparse tabular models", "Teaching feature selection"],
        limitations=["Not ideal when many small effects matter together"],
        mistakes=["Interpreting zero coefficients as proof a feature is useless in all contexts"],
        visuals=["Coefficient plot", "Alpha sweep curve"],
    ),
    "Decision Tree Regressor": _entry(
        explanation="Splits the feature space into rectangular regions and predicts one value per region.",
        intuition="The model asks a sequence of threshold questions and gives a typical answer inside each final leaf.",
        assumptions=["Few assumptions about shape", "Patterns can be approximated by rules"],
        strengths=["Captures non-linearity", "Very visual"],
        weaknesses=["High variance", "Can memorize noise"],
        use_cases=["Rule-based regression", "Teaching overfitting"],
        limitations=["Piecewise predictions can be jagged"],
        mistakes=["Letting the tree grow deep and trusting the training score"],
        visuals=["Tree summary", "Prediction vs true", "Validation curve"],
    ),
    "Random Forest Regressor": _entry(
        explanation="Averages many trees to reduce the instability of a single tree.",
        intuition="Each tree sees a slightly different view of the data, and the ensemble smooths out individual mistakes.",
        assumptions=["Non-linear structure exists", "Enough data is available for many trees"],
        strengths=["Strong general-purpose regressor", "Little manual preprocessing"],
        weaknesses=["Harder to interpret than one tree", "Can be computationally heavier"],
        use_cases=["Tabular regression", "Feature importance exploration"],
        limitations=["Predictions are ensemble averages, so local reasoning is less direct"],
        mistakes=["Ignoring the effect of max_depth and min_samples_leaf on variance"],
        visuals=["Feature importance", "Residual plot", "Model comparison bars"],
    ),
    "Support Vector Regressor": _entry(
        explanation="Fits a function by balancing margin size, tolerance, and kernel flexibility.",
        intuition="Points outside a smooth tolerance tube matter most, and kernels can bend the function.",
        assumptions=["Scaling matters", "Hyperparameters need tuning"],
        strengths=["Powerful with smooth non-linear structure", "Good margin-based teaching example"],
        weaknesses=["Sensitive to C and gamma", "Can be slow on larger datasets"],
        use_cases=["Medium-sized regression datasets", "Kernel demonstrations"],
        limitations=["Less transparent than linear or tree models"],
        mistakes=["Changing C without considering gamma and scaling"],
        visuals=["Validation curves", "Prediction vs true", "Two-parameter heatmap"],
    ),
    "Gradient Boosting Regressor": _entry(
        explanation="Builds a sequence of small trees that correct the residuals of earlier trees.",
        intuition="Each step asks where the current model is still wrong and adds a small correction.",
        assumptions=["Tabular signal with interactions", "Learning rate and number of stages must be balanced"],
        strengths=["Strong performance", "Good for teaching additive modeling"],
        weaknesses=["Sequential training", "Can overfit when too aggressive"],
        use_cases=["Tabular regression", "Hyperparameter tradeoff lessons"],
        limitations=["Less intuitive than one tree or linear model"],
        mistakes=["Increasing both learning_rate and n_estimators without checking test performance"],
        visuals=["Validation curve", "Feature importance", "Residual plot"],
    ),
    "MLP Regressor": _entry(
        explanation="Learns non-linear regression by composing multiple hidden layers.",
        intuition="Each layer transforms the representation so later layers can fit more complex patterns.",
        assumptions=["Scaled inputs", "Training is iterative and may need tuning"],
        strengths=["Flexible function approximation", "Shows neural-network capacity well"],
        weaknesses=["Harder to interpret", "Optimization may be unstable"],
        use_cases=["Tabular neural demo", "Teaching architecture and regularization"],
        limitations=["Usually not the first-choice classical baseline on small tabular data"],
        mistakes=["Adding many layers before checking whether preprocessing and max_iter are sufficient"],
        visuals=["Learning curve", "Prediction vs true", "Hyperparameter sweep"],
    ),
    "Logistic Regression": _entry(
        explanation="Predicts class probabilities using a linear score passed through a logistic function.",
        intuition="The model builds one weighted score and turns it into probability-like outputs.",
        assumptions=["Class boundary is roughly linear in feature space", "Features should be scaled"],
        strengths=["Fast and interpretable", "Strong baseline"],
        weaknesses=["Limited to linear boundaries unless features are engineered", "Can miss complex patterns"],
        use_cases=["Baseline classifier", "Probability and coefficient teaching"],
        limitations=["Sensitive to poorly scaled inputs and heavy class overlap"],
        mistakes=["Treating a good accuracy score as proof the boundary is complex"],
        visuals=["Coefficient plot", "ROC curve", "Confusion matrix"],
    ),
    "K-Nearest Neighbors": _entry(
        explanation="Classifies a point by the labels of its nearby neighbors.",
        intuition="Prediction is based on local agreement in feature space.",
        assumptions=["Nearby points have similar labels", "Distance measure is meaningful"],
        strengths=["Very intuitive", "Easy decision-boundary demos"],
        weaknesses=["Sensitive to scale", "Prediction slows as data grows"],
        use_cases=["Small classification datasets", "Bias-variance demonstrations"],
        limitations=["Struggles when irrelevant features distort distance"],
        mistakes=["Using unscaled features and then tuning K without fixing preprocessing"],
        visuals=["Decision boundary", "Validation curve", "Class distribution"],
    ),
    "Decision Tree Classifier": _entry(
        explanation="Splits features into yes/no rules until leaves become class-specific.",
        intuition="The model keeps asking questions that reduce class mixing.",
        assumptions=["Few shape assumptions", "Useful signal can be separated by threshold rules"],
        strengths=["Highly interpretable", "Works with non-linear interactions"],
        weaknesses=["Very easy to overfit", "Small data changes can change the tree a lot"],
        use_cases=["Rule-based classification", "Overfitting demonstrations"],
        limitations=["Deep trees may look convincing while generalizing poorly"],
        mistakes=["Trusting a perfect training confusion matrix"],
        visuals=["Tree summary", "Decision boundary", "Validation curve"],
    ),
    "Random Forest Classifier": _entry(
        explanation="Combines many decision trees built on random subsets to improve stability.",
        intuition="Each tree is a noisy opinion, and the forest votes across many opinions.",
        assumptions=["Tabular signal with interactions", "Enough data for multiple trees"],
        strengths=["Strong default classifier", "Robust and flexible"],
        weaknesses=["Less transparent", "Larger model footprint"],
        use_cases=["General tabular classification", "Feature importance comparisons"],
        limitations=["Feature importance can be biased toward high-cardinality variables"],
        mistakes=["Ignoring inference time when comparing with simpler models"],
        visuals=["Feature importance", "ROC curve", "Comparison bars"],
    ),
    "Support Vector Machine": _entry(
        explanation="Finds a margin-maximizing separator, optionally in a transformed feature space.",
        intuition="Only the most informative boundary points, the support vectors, determine the separator.",
        assumptions=["Scaled features", "Kernel and regularization must be tuned"],
        strengths=["Excellent boundary control", "Strong medium-sized classifier"],
        weaknesses=["Hyperparameter-sensitive", "Less intuitive probability estimates"],
        use_cases=["Non-linear classification", "Margin and kernel demos"],
        limitations=["Can be slower and harder to interpret"],
        mistakes=["Changing kernel and C without watching how the decision boundary changes"],
        visuals=["Decision boundary", "ROC curve", "C/gamma heatmap"],
    ),
    "Naive Bayes": _entry(
        explanation="Models each class with simple feature distributions and combines them probabilistically.",
        intuition="It treats each feature as contributing evidence toward a class independently of the others.",
        assumptions=["Conditional independence between features", "Class-conditional distributions are simple"],
        strengths=["Fast", "Good conceptual probability model"],
        weaknesses=["Assumptions are strong", "Can be outperformed when features interact heavily"],
        use_cases=["Simple baselines", "Probability reasoning"],
        limitations=["Independence assumption is rarely exactly true"],
        mistakes=["Assuming fast performance means the model understood complex interactions"],
        visuals=["Confusion matrix", "Probability outputs"],
    ),
    "Gradient Boosting Classifier": _entry(
        explanation="Adds weak trees one after another to reduce classification error.",
        intuition="Later trees focus on examples the earlier ensemble still handles poorly.",
        assumptions=["Tabular signal and interactions", "Hyperparameters should be tuned together"],
        strengths=["Strong classifier", "Clear additive-learning story"],
        weaknesses=["Can overfit", "Sequential training is slower than random forests"],
        use_cases=["Tabular classification", "Learning-rate tradeoff lessons"],
        limitations=["Less transparent than logistic regression or one tree"],
        mistakes=["Treating more trees as always better without lowering learning_rate"],
        visuals=["Validation curve", "Feature importance", "ROC curve"],
    ),
    "AdaBoost Classifier": _entry(
        explanation="Reweights hard examples so later weak learners focus on them more.",
        intuition="Examples that were misclassified get more attention in the next round.",
        assumptions=["Weak learners can improve incrementally", "Labels are not too noisy"],
        strengths=["Simple boosting concept", "Good instructional ensemble"],
        weaknesses=["Sensitive to noisy points", "Often weaker than gradient boosting"],
        use_cases=["Teaching boosting ideas", "Compact ensemble baseline"],
        limitations=["Performance can degrade on noisy classification tasks"],
        mistakes=["Increasing learning_rate and n_estimators together without checking stability"],
        visuals=["Validation curve", "Comparison bars", "Confusion matrix"],
    ),
    "MLP Classifier": _entry(
        explanation="Neural network classifier with one or more hidden layers.",
        intuition="Hidden layers learn intermediate feature representations that help separate classes.",
        assumptions=["Scaled inputs", "Optimization settings matter"],
        strengths=["Flexible", "Good for teaching hidden layers"],
        weaknesses=["Less interpretable", "Can require more tuning"],
        use_cases=["Tabular neural demo", "Architecture experiments"],
        limitations=["Often outperformed by tree ensembles on small tabular datasets"],
        mistakes=["Increasing architecture size before checking convergence and regularization"],
        visuals=["Learning curve", "Hyperparameter sweep", "Confusion matrix"],
    ),
}


def get_model_help(name: str) -> dict[str, object]:
    return MODEL_HELP[name]
